# Generated by Django 4.2.3 on 2023-09-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalRecord',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='records.timestampmixin')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('naId', models.CharField(blank=True, max_length=14, null=True)),
                ('hioId', models.CharField(blank=True, max_length=14, null=True, verbose_name='رقم الحاسب')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('illType', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع المرض')),
                ('drugType', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الأدوية المنصرفة')),
                ('drugAmount', models.CharField(blank=True, max_length=255, null=True, verbose_name='كمية الأدوية المنصرفة')),
                ('drugUnit', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوحدة الدوائية')),
            ],
            bases=('records.timestampmixin', models.Model),
        ),
    ]
