# Generated by Django 4.0.6 on 2023-10-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalrecord',
            name='naId',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='الرقم القومى'),
        ),
    ]
