# Generated by Django 4.2.3 on 2023-10-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_finalrecord_ayada'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalrecord',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم المستخدم'),
        ),
    ]
