# Generated by Django 4.2.3 on 2023-10-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_finalrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userayada',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
